name: tool_track
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5
  google_maps_flutter: ^2.2.7
  geolocator: ^9.0.2
  map_picker: ^0.0.3
  geocoding: ^2.1.0
  flutter_nfc_kit: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
